-- Insertion des 22 régions de Madagascar
INSERT INTO region (id, nom, created_at, modified_at) VALUES
('RG01', 'Analamanga', NOW(), NULL),
('RG02', 'Vakinankaratra', NOW(), NULL),
('RG03', 'Itasy', NOW(), NULL),
('RG04', 'Bongolava', NOW(), NULL),
('RG05', 'Haute Matsiatra', NOW(), NULL),
('RG06', 'Amoron''i Mania', NOW(), NULL),
('RG07', 'Atsinanana', NOW(), NULL),
('RG08', 'Analanjirofo', NOW(), NULL),
('RG09', 'Sava', NOW(), NULL),
('RG10', 'Diana', NOW(), NULL),
('RG11', 'Sofia', NOW(), NULL),
('RG12', 'Boeny', NOW(), NULL),
('RG13', 'Melaky', NOW(), NULL),
('RG14', 'Betsiboka', NOW(), NULL),
('RG15', 'Alaotra-Mangoro', NOW(), NULL),
('RG16', 'Androy', NOW(), NULL),
('RG17', 'Anosy', NOW(), NULL),
('RG18', 'Atsimo-Andrefana', NOW(), NULL),
('RG19', 'Atsimo-Atsinanana', NOW(), NULL),
('RG20', 'Menabe', NOW(), NULL),
('RG21', 'Haute Matsiatra', NOW(), NULL),
('RG22', 'Diana', NOW(), NULL);