# server.port = 8080
# spring.application.name=manage

# spring.datasource.url=jdbc:postgresql://localhost:5432/hr_management
# spring.datasource.username=postgres
# spring.datasource.password=lalatiana

# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# # spring.jpa.hibernate.ddl-auto=update
# spring.jpa.hibernate.ddl-auto=none 
# Forcer le fuseau horaire Madagascar
spring.jackson.time-zone=Indian/Antananarivo
user.timezone=Indian/Antananarivo 

server.port=8080
spring.application.name=manage

# Configuration PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/hr_management
spring.datasource.username=postgres
spring.datasource.password=postgres

# Configuration JPA/Hibernate - CRÉATION UNIQUEMENT SI N'EXISTENT PAS
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# spring.jpa.hibernate.ddl-auto=update 
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.format_sql=true 

# Pour les relations et contraintes
# spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
# spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false 

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=rakotovaolalatiana2@gmail.com
spring.mail.password=g a c d c v h b p l s i k g p b
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
