-- emergency_contact test data
BEGIN;
INSERT INTO emergency_contact (id, contact, email, adresse, created_at, modified_at) VALUES ('EC-001', 'Contact 1', 'urgence1@test.smartdev.mg', 'Lot II A 12, Antananarivo', 'NOW()', 'NOW()');
INSERT INTO emergency_contact (id, contact, email, adresse, created_at, modified_at) VALUES ('EC-002', 'Contact 2', 'urgence2@test.smartdev.mg', 'Lot IV B 07, Antsirabe', 'NOW()', 'NOW()');
INSERT INTO emergency_contact (id, contact, email, adresse, created_at, modified_at) VALUES ('EC-003', 'Contact 3', 'urgence3@test.smartdev.mg', 'Lot III D 45, Antsirabe', 'NOW()', 'NOW()');
INSERT INTO emergency_contact (id, contact, email, adresse, created_at, modified_at) VALUES ('EC-004', 'Contact 4', 'urgence4@test.smartdev.mg', 'Lot II A 12, Toliara', 'NOW()', 'NOW()');
INSERT INTO emergency_contact (id, contact, email, adresse, created_at, modified_at) VALUES ('EC-005', 'Contact 5', 'urgence5@test.smartdev.mg', 'Lot I E 03, Antananarivo', 'NOW()', 'NOW()');
INSERT INTO emergency_contact (id, contact, email, adresse, created_at, modified_at) VALUES ('EC-006', 'Contact 6', 'urgence6@test.smartdev.mg', 'Lot I E 03, Toamasina', 'NOW()', 'NOW()');
INSERT INTO emergency_contact (id, contact, email, adresse, created_at, modified_at) VALUES ('EC-007', 'Contact 7', 'urgence7@test.smartdev.mg', 'Lot II A 12, Antananarivo', 'NOW()', 'NOW()');
INSERT INTO emergency_contact (id, contact, email, adresse, created_at, modified_at) VALUES ('EC-008', 'Contact 8', 'urgence8@test.smartdev.mg', 'Lot II A 12, Antsirabe', 'NOW()', 'NOW()');
INSERT INTO emergency_contact (id, contact, email, adresse, created_at, modified_at) VALUES ('EC-009', 'Contact 9', 'urgence9@test.smartdev.mg', 'Lot III D 45, Mahajanga', 'NOW()', 'NOW()');
INSERT INTO emergency_contact (id, contact, email, adresse, created_at, modified_at) VALUES ('EC-010', 'Contact 10', 'urgence10@test.smartdev.mg', 'Lot I E 03, Antananarivo', 'NOW()', 'NOW()');
INSERT INTO emergency_contact (id, contact, email, adresse, created_at, modified_at) VALUES ('EC-011', 'Contact 11', 'urgence11@test.smartdev.mg', 'Lot I E 03, Antsirabe', 'NOW()', 'NOW()');
INSERT INTO emergency_contact (id, contact, email, adresse, created_at, modified_at) VALUES ('EC-012', 'Contact 12', 'urgence12@test.smartdev.mg', 'Lot I E 03, Toamasina', 'NOW()', 'NOW()');
INSERT INTO emergency_contact (id, contact, email, adresse, created_at, modified_at) VALUES ('EC-013', 'Contact 13', 'urgence13@test.smartdev.mg', 'Lot III D 45, Toamasina', 'NOW()', 'NOW()');
INSERT INTO emergency_contact (id, contact, email, adresse, created_at, modified_at) VALUES ('EC-014', 'Contact 14', 'urgence14@test.smartdev.mg', 'Lot I E 03, Fianarantsoa', 'NOW()', 'NOW()');
INSERT INTO emergency_contact (id, contact, email, adresse, created_at, modified_at) VALUES ('EC-015', 'Contact 15', 'urgence15@test.smartdev.mg', 'Lot II A 12, Antsiranana', 'NOW()', 'NOW()');
INSERT INTO emergency_contact (id, contact, email, adresse, created_at, modified_at) VALUES ('EC-016', 'Contact 16', 'urgence16@test.smartdev.mg', 'Lot III D 45, Toliara', 'NOW()', 'NOW()');
INSERT INTO emergency_contact (id, contact, email, adresse, created_at, modified_at) VALUES ('EC-017', 'Contact 17', 'urgence17@test.smartdev.mg', 'Lot V C 19, Fianarantsoa', 'NOW()', 'NOW()');
INSERT INTO emergency_contact (id, contact, email, adresse, created_at, modified_at) VALUES ('EC-018', 'Contact 18', 'urgence18@test.smartdev.mg', 'Lot IV B 07, Antsirabe', 'NOW()', 'NOW()');
INSERT INTO emergency_contact (id, contact, email, adresse, created_at, modified_at) VALUES ('EC-019', 'Contact 19', 'urgence19@test.smartdev.mg', 'Lot III D 45, Antsiranana', 'NOW()', 'NOW()');
INSERT INTO emergency_contact (id, contact, email, adresse, created_at, modified_at) VALUES ('EC-020', 'Contact 20', 'urgence20@test.smartdev.mg', 'Lot IV B 07, Antananarivo', 'NOW()', 'NOW()');
INSERT INTO emergency_contact (id, contact, email, adresse, created_at, modified_at) VALUES ('EC-021', 'Contact 21', 'urgence21@test.smartdev.mg', 'Lot II A 12, Toamasina', 'NOW()', 'NOW()');
INSERT INTO emergency_contact (id, contact, email, adresse, created_at, modified_at) VALUES ('EC-022', 'Contact 22', 'urgence22@test.smartdev.mg', 'Lot II A 12, Fianarantsoa', 'NOW()', 'NOW()');
INSERT INTO emergency_contact (id, contact, email, adresse, created_at, modified_at) VALUES ('EC-023', 'Contact 23', 'urgence23@test.smartdev.mg', 'Lot IV B 07, Mahajanga', 'NOW()', 'NOW()');
INSERT INTO emergency_contact (id, contact, email, adresse, created_at, modified_at) VALUES ('EC-024', 'Contact 24', 'urgence24@test.smartdev.mg', 'Lot IV B 07, Antsiranana', 'NOW()', 'NOW()');
INSERT INTO emergency_contact (id, contact, email, adresse, created_at, modified_at) VALUES ('EC-025', 'Contact 25', 'urgence25@test.smartdev.mg', 'Lot II A 12, Toliara', 'NOW()', 'NOW()');
INSERT INTO emergency_contact (id, contact, email, adresse, created_at, modified_at) VALUES ('EC-026', 'Contact 26', 'urgence26@test.smartdev.mg', 'Lot V C 19, Mahajanga', 'NOW()', 'NOW()');
INSERT INTO emergency_contact (id, contact, email, adresse, created_at, modified_at) VALUES ('EC-027', 'Contact 27', 'urgence27@test.smartdev.mg', 'Lot II A 12, Toamasina', 'NOW()', 'NOW()');
INSERT INTO emergency_contact (id, contact, email, adresse, created_at, modified_at) VALUES ('EC-028', 'Contact 28', 'urgence28@test.smartdev.mg', 'Lot II A 12, Mahajanga', 'NOW()', 'NOW()');
INSERT INTO emergency_contact (id, contact, email, adresse, created_at, modified_at) VALUES ('EC-029', 'Contact 29', 'urgence29@test.smartdev.mg', 'Lot IV B 07, Antsiranana', 'NOW()', 'NOW()');
INSERT INTO emergency_contact (id, contact, email, adresse, created_at, modified_at) VALUES ('EC-030', 'Contact 30', 'urgence30@test.smartdev.mg', 'Lot I E 03, Antsiranana', 'NOW()', 'NOW()');
COMMIT;